### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by billh0420** [digama0/mmj2#51]
I am using the Eclipse IDE. There are many warnings "The serializable class  does not declare a static final serialVersionUID field of type long". One suggested way to remove the warning is to add "@SuppressWarnings("serial")". I am willing to make these changes and submit a pull request from my fork. Is this worthwhile doing? Will it be accepted? Thanks.

**Comment by digama0** [comment]
I believe you can suppress this warning in eclipse altogether. We don't do any serialization so adding this annotation on every class sounds like pure noise.
