### ISSUE TITLE
Eclipse IDE reformats existing code style when making changes

### ISSUE THREAD

**Issue by billh0420** [digama0/mmj2#53]
I am modifying the file ProofAsstGUI.java with the Eclipse IDE. The Eclipse IDE automatically corrects code style according to the preference in Java->Code Style->Formatter setting. I modified the default setting to keep "{ }" on one line to match the current mmj2 style. However, there are still other differences: see lines 471, 1238, 1264, and 1449 where the "{" is not under "new".

Question one: Is this intentional? I prefer it under "new".

There is also a difference for line 2093. The original is:

     `
        try (final BufferedWriter w = new BufferedWriter(new FileWriter(file))){
            final String s = proofTextPane.getText();
            w.write(s, 0, s.length());
        } catch (final Throwable e) {

`

My version is:

     `
        try (
            final BufferedWriter w = new BufferedWriter(new FileWriter(file)))
        {
            final String s = proofTextPane.getText();
            w.write(s, 0, s.length());
        } catch (final Throwable e) {
`

I am not worry about this case.

Question two: Should we all be using the same IDE with the same code style settings? 

Otherwise, every time someone does a push, unnecessary changes will be made due only to code style requirements.

**Comment by digama0** [comment]
I would recommend turning off the formatter and/or only formatting new code. I have no interest in patches that battle with formatting settings.
